# Generated by Django 5.1.3 on 2024-11-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsSuggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('date_time_created', models.DateTimeField(auto_now_add=True, verbose_name='date time created')),
            ],
            options={
                'verbose_name': 'comments and suggestions ',
                'verbose_name_plural': 'comments and suggestions ',
            },
        ),
    ]
