# Generated by Django 5.1.3 on 2024-11-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentssuggestions',
            options={'verbose_name': 'انتقادات و پیشنهاد ها', 'verbose_name_plural': 'انتقادات و پیشنهاد ها'},
        ),
        migrations.AlterField(
            model_name='commentssuggestions',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='commentssuggestions',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
    ]
