# Generated by Django 5.1.3 on 2024-11-28 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('date_time_created', models.DateField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='FoodQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_quality', models.CharField(choices=[('4', 'perfect'), ('3', 'good'), ('2', 'manual'), ('1', 'bad')], max_length=50, verbose_name='quality')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.food', verbose_name='food')),
            ],
        ),
    ]
