# Generated by Django 5.1.3 on 2024-11-28 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurStrengths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Strength', models.CharField(max_length=255, verbose_name='strength')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('date_time_created', models.DateTimeField(auto_now_add=True, verbose_name='date time created')),
            ],
            options={
                'verbose_name': 'Strength',
                'verbose_name_plural': 'Strength',
            },
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'غذا', 'verbose_name_plural': 'غذا'},
        ),
        migrations.AlterModelOptions(
            name='foodquality',
            options={'verbose_name': 'کیفیت غذا', 'verbose_name_plural': 'کیفیت غذا'},
        ),
        migrations.AlterField(
            model_name='food',
            name='date_time_created',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='foodquality',
            name='choice_quality',
            field=models.CharField(choices=[('4', 'عالی'), ('3', 'خوب'), ('2', 'معمولی'), ('1', 'بد')], max_length=50, verbose_name='کیفیت'),
        ),
        migrations.AlterField(
            model_name='foodquality',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.food', verbose_name='غذا'),
        ),
        migrations.CreateModel(
            name='SurveyAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes_or_no', models.BooleanField(default=False, verbose_name='yes or no')),
                ('date_time_created', models.DateTimeField(auto_now_add=True, verbose_name='date time created')),
                ('strength', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.ourstrengths', verbose_name='strength')),
            ],
            options={
                'verbose_name': 'survey about us',
                'verbose_name_plural': 'survey about us',
            },
        ),
    ]
