# Generated by Django 5.1.3 on 2024-11-29 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_rename_strength_ourstrengths_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('date_time_created', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collection',
            },
        ),
        migrations.AlterField(
            model_name='ourstrengths',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='surveyaboutus',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costomer_score', models.CharField(choices=[('4', 'عالی'), ('3', 'خوب'), ('2', 'معمولی'), ('1', 'بد')], max_length=50, verbose_name='customer score')),
                ('date_time_created', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('cleaning_the_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.collectioncleaning', verbose_name='cleannig area')),
            ],
            options={
                'verbose_name': 'coustomer score for cleaning ',
                'verbose_name_plural': 'coustomer score for cleaning ',
            },
        ),
    ]
